package layer.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.HashMap;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@RequiredArgsConstructor
@Builder
@DynamoDBTable(tableName = "it-marathon-v3-user-db")
public class User {

    @DynamoDBHashKey(attributeName = "email")
    @DynamoDBAutoGeneratedKey
    private String email;

    @DynamoDBIndexHashKey(attributeName = "country",
            globalSecondaryIndexNames = {
                    "country-name-index",
                    "country-birthday-index",
                    "country-location-index",
                    "country-registration-index"
            })
    private String country;

    @DynamoDBIndexRangeKey(attributeName = "name",
            globalSecondaryIndexName = "country-name-index")
    private String name;

    @DynamoDBIndexRangeKey(attributeName = "location",
            globalSecondaryIndexName = "country-location-index")
    private String location;

    @DynamoDBIndexRangeKey(attributeName = "birthday",
            globalSecondaryIndexName = "country-birthday-index")
    private Long birthday;

    @DynamoDBIndexRangeKey(attributeName = "registration",
            globalSecondaryIndexName = "country-registration-index")
    private Long registration;

    @DynamoDBAttribute(attributeName = "avatar")
    private String avatar;

    @DynamoDBAttribute(attributeName = "about")
    private String about;

    @DynamoDBAttribute(attributeName = "interests")
    private List<String> interests;

    @DynamoDBAttribute(attributeName = "social_media")
    private HashMap<String, String> socialMedia;

    @DynamoDBAttribute(attributeName = "privacy")
    private HashMap<String, Boolean> privacy;

}